# Lorenz ML DA Configuration

dataset:
  system_type: '63' # '63' or '96'
  dt: 0.01
  ns: 5000
  save_dt: 10
  std: 0.001
  prev_time_steps: 4

model:
  type: 'ResDenseNN' # 'DenseNN' or 'ResDenseNN'
  hidden_layers: [64, 64, 32, 16]
  hidden_activation: 'ReLU'
  output_activation: null

training:
  num_epochs: 400
  batch_size: 64
  learning_rate: 0.001
  n_trials: 3
  early_stopping_patience: 10

paths:
  outputs: 'outputs'
  models: 'models'
  runs: 'runs'
